@startuml
title 车辆状态变化图

state ifobu <<choice>>

[*] --> 进入车道
进入车道 --> ifobu
ifobu --> OBU交易中 : 存在OBU
OBU交易中 --> 可驶离 : 交易成功
ifobu --> 人工交易中 : 不存在OBU
人工交易中 --> 可驶离 : 交易成功
OBU交易中-right-> 人工交易中 : 交易失败转人工窗口处理
可驶离--> 离开收费站 : 抬杆
离开收费站-->[*]

state OBU交易中{
    [*] -->等待OBU基础信息
    等待OBU基础信息--> 等待OBU基础信息 : Repeat search
    等待OBU基础信息--> 等待OBU车辆信息 : 校验成功

    等待OBU车辆信息--> 等待IC卡信息: 校验成功
    等待OBU车辆信息--> 等待OBU基础信息: 校验失败

    等待IC卡信息--> 等待交易结果: 校验成功
    等待IC卡信息--> 等待OBU基础信息: 校验失败

    等待交易结果--> 等待OBU基础信息: 校验失败/\n计费失败/\n扣款失败
    等待交易结果--> [*]: 交易成功
}

state 人工交易中 {

    state mtrans <<fork>>
    state mtrans_join <<join>>

    [*] --> mtrans
    mtrans --> 车辆信息确定中
    mtrans --> 入口确定中

    车辆信息确定中-->mtrans_join
    入口确定中-->mtrans_join

    mtrans_join --> 等待告知通行费
    等待告知通行费 --> 通行费支付中 : 司机确认通行费无误
    通行费支付中--> 获取发票中 : 司机支付成功
    获取发票中-->[*] : 发票交付司机

    等待告知通行费 -up[#blue]-> 入口确定中 : 司机认为通行费有误/\n计费失败
    等待告知通行费 -up[#blue]-> 车辆信息确定中 : 司机认为通行费有误/\n计费失败

    通行费支付中 -up[#blue]-> 车辆信息确定中: 司机认为通行费有误\n重新确认车辆信息
    通行费支付中 -up[#blue]-> 入口确定中: 司机认为通行费有误\n重新确认入口信息

    state 车辆信息确定中{
        state vinfo <<fork>>
        state vinfo_join <<join>>

        [*]-->vinfo
        vinfo--> 抓拍设备识别车牌 : 设备抓拍识别
        抓拍设备识别车牌 : 车牌校验[有设备识别车牌] / 人工确认或修改车牌
        抓拍设备识别车牌 : 车牌校验[无设备识别车牌] / 人工输入车牌
        抓拍设备识别车牌 --> 车牌已确定 : 车牌校验通过
        vinfo--> 车型已确定 : 人工判断车型
        vinfo--> 车类已确定 : 人工判断车类
        vinfo--> 用户类型已确定 : 第三方接口确认用户类型
        用户类型已确定 : 使用接口返回用户类型
        用户类型已确定 : 使用默认用户类型[接口查询失败]
        车型已确定 --> vinfo_join
        车牌已确定 --> vinfo_join
        车类已确定 --> vinfo_join
        用户类型已确定 --> vinfo_join
        vinfo_join-->[*]
    }
    


    state 入口确定中{
        state einfo <<choice>>

        [*] --> einfo
        einfo --> 通行介质确定为CPC卡 : 司机上交CPC卡
        einfo --> 通行介质确定为ETC卡 : 司机上ETC卡
        einfo --> 通行介质确定为纸卡 : 司机上交纸卡
        einfo --> 通行介质确定为无卡 : 司机表示无卡

        通行介质确定为CPC卡 --> 入口已确定 : 读卡成功[卡内入口信息校验通过]
        通行介质确定为ETC卡 --> 入口已确定 : 读卡成功[卡内入口信息校验通过]
        通行介质确定为纸卡 --> 入口已确定 : 输入纸卡信息
        通行介质确定为无卡 : 根据车牌在线查询入口信息
        通行介质确定为无卡 --> 入口已确定 : 在线查询入口成功
        通行介质确定为无卡 -[#blue]-> 手工选站 : 在线查询入口失败

        通行介质确定为CPC卡 -[#blue]-> 卡无效 : 卡内入口信息校验不通过/读卡失败/卡损坏
        通行介质确定为ETC卡 -[#blue]-> 卡无效 : 卡内入口信息校验不通过/读卡失败/卡损坏
        卡无效 : 人工输入卡号在线查询入口信息
        卡无效 --> 入口已确定 : 在线查询入口成功
        卡无效 -[#blue]-> 手工选站 : 在线查询入口失败

        手工选站 --> 入口已确定
        入口已确定-->[*]
        }

    state 等待告知通行费{
        等待告知通行费 : 计算通行费成功后告知司机
        state judgeCalcType <<choice>>
        [*] --> judgeCalcType

        judgeCalcType --> 卡内信息计费 : 入口信息为读卡获得[卡内计费信息校验通过]
        judgeCalcType --> 在线计费 : 入口信息为在线查询获得\n入口信息为读卡获得[卡内计费信息校验不通过]
        judgeCalcType --> 兜底计费 : 通行介质为纸卡
        在线计费 -right-> 兜底计费 : 在线计费失败

        卡内信息计费 --> 计费成功告知司机 : 计费成功
        在线计费 --> 计费成功告知司机 : 计费成功
        兜底计费 --> 计费成功告知司机 : 计费成功

        计费成功告知司机 --> [*]
    }

    state 通行费支付中{
        state choosePayType <<choice>>

        [*] --> choosePayType
        choosePayType --> 现金支付 : 司机支付现金
        choosePayType --> ETC卡支付 : 司机交ETC卡
        choosePayType --> 扫码支付 : 司机出示付款码
        choosePayType --> 先行后付 : 司机要求使用先行后付
        choosePayType --> 第三方APP支付 : 司机要求使用第三方APP支付

        现金支付 : 确认现金足够支付本次通行费
        ETC卡支付 : 卡片信息校验通过[读卡成功]/卡片扣款
        扫码支付 : 扫描司机付款码发起在线支付
        先行后付 : 查询是否满足先行后付条件
        第三方APP支付 : 查询第三方APP支付成功信息

        现金支付 -[#blue]-> choosePayType : 现金不足\n重新选择支付方式
        ETC卡支付 -[#blue]-> choosePayType : ETC卡读卡失败\n(非本车卡\n余额不足\n卡片扣款失败等)\n重新选择支付方式
        扫码支付 -[#blue]-> choosePayType : 扫码支付失败\n(扫码失败、超时、余额不足等)\n重新选择支付方式
        先行后付 -[#blue]-> choosePayType : 非先行后付用户\n重新选择支付方式
        第三方APP支付 -[#blue]-> choosePayType : 第三方APP支付失败\n重新选择支付方式

        现金支付 --> 支付成功 : 足额收取现金
        ETC卡支付 --> 支付成功 : ETC卡扣款成功
        扫码支付 --> 支付成功 : 在线支付成功
        先行后付 --> 支付成功 : 满足先行后付条件
        第三方APP支付 --> 支付成功 : 查询到第三方APP\n支付成功信息

        支付成功 --> [*]
    }

    state 获取发票中{
        state needPrint<<choice>>

        [*] --> needPrint
        needPrint --> 打印发票中 : 需要打印发票
        打印发票中 --> 打印发票中 : 打印失败，修复问题后重新打印
        打印发票中 --> 打印完成 : 打印成功
        打印完成 --> 打印发票中 :交付司机\n司机不认可发票\n(模糊、缺字等)
        打印完成 --> [*] : 交付司机\n司机认可发票
        needPrint --> [*] :  不需要打印发票
    }

}

@enduml